package migrate

import (
	"fmt"
	"strconv"
	"strings"
)

// Dialect abstracts the SQL differences between database backends: how
// identifiers are quoted, how bind parameters are spelled, how the automatic
// primary-key column is declared, and how the DSL's abstract column types map
// to concrete SQL. The package ships four implementations, exposed as the
// package-level values [ANSI], [Postgres], [MySQL], and [SQLite].
//
// Dialect is a sealed interface: it has unexported methods, so only the
// dialects provided by this package satisfy it. Select one by name with
// [DialectByName] and bind it to a schema builder with [NewSchema].
type Dialect interface {
	// Name returns the dialect's short lowercase identifier, e.g. "postgres".
	Name() string
	// Quote renders an identifier (table, column, index name) safely quoted for
	// the dialect. Identifiers that are not simple words are returned verbatim
	// so callers may pass expressions to index builders.
	Quote(identifier string) string
	// Placeholder renders the bind-parameter marker for the 1-based position,
	// e.g. "?" for MySQL/SQLite or "$1" for PostgreSQL.
	Placeholder(position int) string

	columnType(spec typeSpec) string
	autoIncrementPK(name string) string
}

// The four dialects supported by the package.
var (
	// ANSI is a conservative, portable SQL dialect: unquoted identifiers, "?"
	// placeholders, and SQL:2003 identity columns. It is the default used by the
	// package-level DSL helpers.
	ANSI Dialect = ansiDialect{}
	// Postgres targets PostgreSQL: double-quoted identifiers, "$n" placeholders,
	// bigserial primary keys, and native jsonb / array / uuid types.
	Postgres Dialect = postgresDialect{}
	// MySQL targets MySQL/MariaDB: backtick-quoted identifiers, "?" placeholders,
	// AUTO_INCREMENT primary keys, and inline ENUM types.
	MySQL Dialect = mysqlDialect{}
	// SQLite targets SQLite: double-quoted identifiers, "?" placeholders, and
	// INTEGER PRIMARY KEY AUTOINCREMENT.
	SQLite Dialect = sqliteDialect{}
)

// DialectByName returns the [Dialect] registered under name (case-insensitive),
// or [ErrUnknownDialect] if none matches. Accepted names are "ansi",
// "postgres" (or "postgresql"/"pg"), "mysql" (or "mariadb"), and "sqlite" (or
// "sqlite3").
func DialectByName(name string) (Dialect, error) {
	switch strings.ToLower(strings.TrimSpace(name)) {
	case "ansi", "sql", "standard":
		return ANSI, nil
	case "postgres", "postgresql", "pg":
		return Postgres, nil
	case "mysql", "mariadb":
		return MySQL, nil
	case "sqlite", "sqlite3":
		return SQLite, nil
	default:
		return nil, fmt.Errorf("%w: %q", ErrUnknownDialect, name)
	}
}

// isSimpleIdent reports whether s is a bare identifier safe to quote as a whole.
// Non-identifiers (expressions like "lower(email)") are left untouched by Quote.
func isSimpleIdent(s string) bool {
	return identRe.MatchString(s)
}

// varchar renders VARCHAR(n), defaulting a non-positive length to 255.
func varchar(limit int) string {
	if limit <= 0 {
		limit = 255
	}
	return fmt.Sprintf("VARCHAR(%d)", limit)
}

// decimalType renders word[(precision[,scale])] from a spec.
func decimalType(word string, s typeSpec) string {
	if s.precision <= 0 {
		return word
	}
	if s.scale > 0 {
		return fmt.Sprintf("%s(%d,%d)", word, s.precision, s.scale)
	}
	return fmt.Sprintf("%s(%d)", word, s.precision)
}

// withPrecision appends "(precision)" to word when precision is positive.
func withPrecision(word string, s typeSpec) string {
	if s.precision > 0 {
		return fmt.Sprintf("%s(%d)", word, s.precision)
	}
	return word
}

// enumValues renders a comma-separated list of quoted enum literals.
func enumValues(vals []string) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		parts[i] = quote(v)
	}
	return strings.Join(parts, ", ")
}

// ---------------------------------------------------------------------------
// ANSI
// ---------------------------------------------------------------------------

type ansiDialect struct{}

func (ansiDialect) Name() string           { return "ansi" }
func (ansiDialect) Quote(id string) string { return id }
func (ansiDialect) Placeholder(int) string { return "?" }
func (ansiDialect) autoIncrementPK(n string) string {
	return n + " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
}

func (d ansiDialect) columnType(s typeSpec) string {
	base := d.base(s)
	if s.array {
		return base + " ARRAY"
	}
	return base
}

func (ansiDialect) base(s typeSpec) string {
	switch s.kind {
	case kindRaw:
		return s.raw
	case kindString:
		return varchar(s.limit)
	case kindText:
		return "TEXT"
	case kindInteger:
		return "INTEGER"
	case kindBigInt:
		return "BIGINT"
	case kindFloat:
		return "DOUBLE PRECISION"
	case kindBoolean:
		return "BOOLEAN"
	case kindDecimal:
		return decimalType("DECIMAL", s)
	case kindTimestamp:
		w := withPrecision("TIMESTAMP", s)
		if s.withTZ {
			return w + " WITH TIME ZONE"
		}
		return w
	case kindDate:
		return "DATE"
	case kindTime:
		w := withPrecision("TIME", s)
		if s.withTZ {
			return w + " WITH TIME ZONE"
		}
		return w
	case kindBinary:
		return "BLOB"
	case kindJSON:
		return "JSON"
	case kindJSONB:
		return "JSONB"
	case kindUUID:
		return "UUID"
	case kindEnum:
		return "VARCHAR(255)"
	default:
		return "TEXT"
	}
}

// ---------------------------------------------------------------------------
// PostgreSQL
// ---------------------------------------------------------------------------

type postgresDialect struct{}

func (postgresDialect) Name() string { return "postgres" }

func (postgresDialect) Quote(id string) string {
	if !isSimpleIdent(id) {
		return id
	}
	return `"` + strings.ReplaceAll(id, `"`, `""`) + `"`
}

func (postgresDialect) Placeholder(pos int) string { return "$" + strconv.Itoa(pos) }

func (postgresDialect) autoIncrementPK(n string) string { return `"` + n + `" BIGSERIAL PRIMARY KEY` }

func (d postgresDialect) columnType(s typeSpec) string {
	base := d.base(s)
	if s.array {
		return base + "[]"
	}
	return base
}

func (postgresDialect) base(s typeSpec) string {
	switch s.kind {
	case kindRaw:
		return s.raw
	case kindString:
		return varchar(s.limit)
	case kindText:
		return "TEXT"
	case kindInteger:
		return "INTEGER"
	case kindBigInt:
		return "BIGINT"
	case kindFloat:
		return "DOUBLE PRECISION"
	case kindBoolean:
		return "BOOLEAN"
	case kindDecimal:
		return decimalType("NUMERIC", s)
	case kindTimestamp:
		w := withPrecision("TIMESTAMP", s)
		if s.withTZ {
			return w + " WITH TIME ZONE"
		}
		return w
	case kindDate:
		return "DATE"
	case kindTime:
		w := withPrecision("TIME", s)
		if s.withTZ {
			return w + " WITH TIME ZONE"
		}
		return w
	case kindBinary:
		return "BYTEA"
	case kindJSON:
		return "JSON"
	case kindJSONB:
		return "JSONB"
	case kindUUID:
		return "UUID"
	case kindEnum:
		return s.enumName // references a CREATE TYPE ... AS ENUM type
	default:
		return "TEXT"
	}
}

// ---------------------------------------------------------------------------
// MySQL
// ---------------------------------------------------------------------------

type mysqlDialect struct{}

func (mysqlDialect) Name() string { return "mysql" }

func (mysqlDialect) Quote(id string) string {
	if !isSimpleIdent(id) {
		return id
	}
	return "`" + strings.ReplaceAll(id, "`", "``") + "`"
}

func (mysqlDialect) Placeholder(int) string { return "?" }

func (mysqlDialect) autoIncrementPK(n string) string {
	return "`" + n + "` BIGINT AUTO_INCREMENT PRIMARY KEY"
}

func (d mysqlDialect) columnType(s typeSpec) string {
	if s.array {
		return "JSON" // MySQL has no array type; store as JSON
	}
	switch s.kind {
	case kindRaw:
		return s.raw
	case kindString:
		return varchar(s.limit)
	case kindText:
		return "TEXT"
	case kindInteger:
		return "INT"
	case kindBigInt:
		return "BIGINT"
	case kindFloat:
		return "DOUBLE"
	case kindBoolean:
		return "TINYINT(1)"
	case kindDecimal:
		return decimalType("DECIMAL", s)
	case kindTimestamp:
		return withPrecision("DATETIME", s)
	case kindDate:
		return "DATE"
	case kindTime:
		return withPrecision("TIME", s)
	case kindBinary:
		return "BLOB"
	case kindJSON, kindJSONB:
		return "JSON"
	case kindUUID:
		return "CHAR(36)"
	case kindEnum:
		return "ENUM(" + enumValues(s.enumVals) + ")"
	default:
		return "TEXT"
	}
}

// ---------------------------------------------------------------------------
// SQLite
// ---------------------------------------------------------------------------

type sqliteDialect struct{}

func (sqliteDialect) Name() string { return "sqlite" }

func (sqliteDialect) Quote(id string) string {
	if !isSimpleIdent(id) {
		return id
	}
	return `"` + strings.ReplaceAll(id, `"`, `""`) + `"`
}

func (sqliteDialect) Placeholder(int) string { return "?" }

func (sqliteDialect) autoIncrementPK(n string) string {
	return `"` + n + `" INTEGER PRIMARY KEY AUTOINCREMENT`
}

func (d sqliteDialect) columnType(s typeSpec) string {
	if s.array {
		return "JSON"
	}
	switch s.kind {
	case kindRaw:
		return s.raw
	case kindString:
		return varchar(s.limit)
	case kindText:
		return "TEXT"
	case kindInteger:
		return "INTEGER"
	case kindBigInt:
		return "BIGINT"
	case kindFloat:
		return "REAL"
	case kindBoolean:
		return "BOOLEAN"
	case kindDecimal:
		return decimalType("DECIMAL", s)
	case kindTimestamp:
		return "DATETIME"
	case kindDate:
		return "DATE"
	case kindTime:
		return "TIME"
	case kindBinary:
		return "BLOB"
	case kindJSON, kindJSONB:
		return "JSON"
	case kindUUID:
		return "VARCHAR(36)"
	case kindEnum:
		return "VARCHAR(255)"
	default:
		return "TEXT"
	}
}
