// Package migrate is a small, dependency-free, ActiveRecord-style schema
// migration toolkit for Go built entirely on top of the standard library's
// database/sql package.
//
// # Overview
//
// A [Migration] carries a monotonically increasing Version, a human readable
// Name, and a pair of directions. A direction may be expressed either as a Go
// function that runs against an open *sql.Tx, or as raw SQL text. A [Migrator]
// wraps a *sql.DB, ensures a bookkeeping table (schema_migrations by default)
// exists, records which versions have been applied, and drives the migrations
// forward and backward.
//
// Every migration runs inside its own transaction. If a migration fails, its
// transaction is rolled back, the version is not recorded, and the run halts
// immediately without touching any later migration. Re-running [Migrator.Migrate]
// is therefore idempotent: only versions that have not yet been recorded are
// applied.
//
// # Loading migrations
//
// Migrations can be registered programmatically with [Migrator.Register] (handy
// for Go migrations) or loaded from a directory / io/fs.FS of files named
//
//	<version>_<name>.up.sql
//	<version>_<name>.down.sql
//
// via [LoadDir] and [LoadFS]. See those functions for the exact grammar.
//
// # Schema DSL
//
// The package ships an ActiveRecord-flavoured schema builder. Package-level
// helpers ([CreateTable], [AddColumn], [AddIndex], [ChangeTable],
// [AddForeignKey], [AddReference], [RenameColumn], [ChangeColumn], ...) emit SQL
// strings you can drop straight into a migration's UpSQL/DownSQL or execute from
// a Go migration. The full column vocabulary is available on [Table]: String,
// Text, Integer, BigInteger, Float, Decimal, Boolean, Date, Time, Timestamp
// (with [Precision] and [WithTimezone]), Binary, JSON, JSONB, UUID, Enum, and
// [Array] columns, plus References.
//
// # Dialects
//
// A [Dialect] captures how a backend quotes identifiers, spells bind
// parameters, declares auto-increment primary keys, and names concrete column
// types. Four dialects are provided: [ANSI] (the default), [Postgres], [MySQL],
// and [SQLite]. The package-level helpers render for [ANSI]; bind another
// dialect with [NewSchema] to get, for example, backtick quoting and
// AUTO_INCREMENT for MySQL, or bigserial and native jsonb/array/uuid types for
// PostgreSQL.
//
// # Reversible changes
//
// [Change] records a sequence of schema operations and derives the inverse
// automatically, so a migration is written once and rolled back for free.
// Operations that cannot be mechanically reversed (a raw Execute, a change of
// column type, or a drop without a rebuild block) mark the change irreversible
// and rolling it back fails with [ErrIrreversibleMigration].
//
// # Seeds and dumps
//
// [Seeder] loads data idempotently, tracking each named seed so it runs at most
// once. [SchemaDump] collects DDL into a single version-stamped, reconstructable
// script analogous to Rails' schema.rb.
//
// # SQL dialect assumptions
//
// The migrator's own bookkeeping statements target a conservative ANSI SQL
// subset regardless of the schema dialect chosen:
//
//   - Bookkeeping bind parameters use the '?' placeholder style (as used by
//     MySQL, SQLite, and the in-memory test driver). Use [Dialect.Placeholder]
//     to render backend-appropriate markers in your own statements.
//   - The bookkeeping auto-increment key is emitted as
//     "BIGINT GENERATED BY DEFAULT AS IDENTITY" (SQL:2003 identity columns).
//   - Referential columns created by [Table.References] follow the Rails
//     convention of "<singular>_id" and a naive "+s" pluralisation for the
//     referenced table name.
//
// These choices are documented so callers know exactly what to expect; they are
// deliberately not clever, because the goal is predictable, greppable output.
package migrate

// Version is the semantic version of this library. It mirrors the VERSION file.
const Version = "0.3.0"
