// Package migrate is a small, dependency-free, ActiveRecord-style schema
// migration toolkit for Go built entirely on top of the standard library's
// database/sql package.
//
// # Overview
//
// A [Migration] carries a monotonically increasing Version, a human readable
// Name, and a pair of directions. A direction may be expressed either as a Go
// function that runs against an open *sql.Tx, or as raw SQL text. A [Migrator]
// wraps a *sql.DB, ensures a bookkeeping table (schema_migrations by default)
// exists, records which versions have been applied, and drives the migrations
// forward and backward.
//
// Every migration runs inside its own transaction. If a migration fails, its
// transaction is rolled back, the version is not recorded, and the run halts
// immediately without touching any later migration. Re-running [Migrator.Migrate]
// is therefore idempotent: only versions that have not yet been recorded are
// applied.
//
// # Loading migrations
//
// Migrations can be registered programmatically with [Migrator.Register] (handy
// for Go migrations) or loaded from a directory / io/fs.FS of files named
//
//	<version>_<name>.up.sql
//	<version>_<name>.down.sql
//
// via [LoadDir] and [LoadFS]. See those functions for the exact grammar.
//
// # Schema DSL
//
// The package also ships a tiny ActiveRecord-flavoured schema builder
// ([CreateTable], [AddColumn], [AddIndex], [DropTable], [RenameColumn], ...)
// that emits SQL strings you can drop straight into a migration's UpSQL/DownSQL
// or execute from a Go migration.
//
// # SQL dialect assumptions
//
// The generated SQL and the migrator's own bookkeeping statements target a
// conservative ANSI SQL subset:
//
//   - Bind parameters use the '?' placeholder style (as used by MySQL, SQLite,
//     and the in-memory test driver). Drivers that require positional
//     parameters such as $1 (PostgreSQL's lib/pq) would need an adapter.
//   - Auto-incrementing primary keys are emitted as
//     "BIGINT GENERATED BY DEFAULT AS IDENTITY" (SQL:2003 identity columns).
//   - Column types map to portable ANSI spellings: VARCHAR(n), TEXT, INTEGER,
//     BIGINT, BOOLEAN, TIMESTAMP, DATE, DOUBLE PRECISION.
//   - Referential columns created by Table.References follow the Rails
//     convention of "<singular>_id" and a naive "+s" pluralisation for the
//     referenced table name.
//
// These choices are documented so callers know exactly what to expect; they are
// deliberately not clever, because the goal is predictable, greppable output.
package migrate

// Version is the semantic version of this library. It mirrors the VERSION file.
const Version = "0.1.0"
