package migrate

import "testing"

func TestCreateTableDSL(t *testing.T) {
	got := CreateTable("users", func(t *Table) {
		t.String("email", NotNull(), Unique())
		t.String("name", Limit(100))
		t.Integer("age")
		t.Boolean("active", NotNull(), Default(true))
		t.References("account", WithForeignKey(), ReferenceNotNull())
		t.Timestamps()
	})

	want := "CREATE TABLE users (\n" +
		"\tid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
		"\temail VARCHAR(255) NOT NULL UNIQUE,\n" +
		"\tname VARCHAR(100),\n" +
		"\tage INTEGER,\n" +
		"\tactive BOOLEAN NOT NULL DEFAULT TRUE,\n" +
		"\taccount_id BIGINT NOT NULL,\n" +
		"\tcreated_at TIMESTAMP NOT NULL,\n" +
		"\tupdated_at TIMESTAMP NOT NULL,\n" +
		"\tFOREIGN KEY (account_id) REFERENCES accounts (id)\n" +
		")"
	if got != want {
		t.Fatalf("CreateTable mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestCreateTableWithoutID(t *testing.T) {
	got := CreateTable("join_table", func(t *Table) {
		t.BigInteger("left_id", NotNull())
		t.BigInteger("right_id", NotNull())
	}, WithoutID())
	want := "CREATE TABLE join_table (\n" +
		"\tleft_id BIGINT NOT NULL,\n" +
		"\tright_id BIGINT NOT NULL\n" +
		")"
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestStringDefaultQuoting(t *testing.T) {
	got := CreateTable("t", func(t *Table) {
		t.String("status", NotNull(), Default("it's on"))
	}, WithoutID())
	want := "CREATE TABLE t (\n\tstatus VARCHAR(255) NOT NULL DEFAULT 'it''s on'\n)"
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestAlterHelpers(t *testing.T) {
	cases := []struct{ got, want string }{
		{AddColumn("users", "nickname", "VARCHAR", Limit(50)), "ALTER TABLE users ADD COLUMN nickname VARCHAR(50)"},
		{DropColumn("users", "nickname"), "ALTER TABLE users DROP COLUMN nickname"},
		{RenameColumn("users", "name", "full_name"), "ALTER TABLE users RENAME COLUMN name TO full_name"},
		{RenameTable("users", "members"), "ALTER TABLE users RENAME TO members"},
		{DropTable("users"), "DROP TABLE users"},
		{DropTableIfExists("users"), "DROP TABLE IF EXISTS users"},
		{DropIndex("index_users_on_email"), "DROP INDEX index_users_on_email"},
	}
	for i, c := range cases {
		if c.got != c.want {
			t.Fatalf("case %d: got %q, want %q", i, c.got, c.want)
		}
	}
}

func TestAddIndex(t *testing.T) {
	if got, want := AddIndex("users", []string{"email"}), "CREATE INDEX index_users_on_email ON users (email)"; got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
	if got, want := AddIndex("users", []string{"first", "last"}, UniqueIndex()),
		"CREATE UNIQUE INDEX index_users_on_first_and_last ON users (first, last)"; got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
	if got, want := AddIndex("users", []string{"email"}, IndexName("custom_idx")),
		"CREATE INDEX custom_idx ON users (email)"; got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
}

func TestReferenceCustomTable(t *testing.T) {
	got := CreateTable("memberships", func(t *Table) {
		t.References("person", ReferenceTable("people"), WithForeignKey())
	}, WithoutID())
	want := "CREATE TABLE memberships (\n" +
		"\tperson_id BIGINT,\n" +
		"\tFOREIGN KEY (person_id) REFERENCES people (id)\n" +
		")"
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}
